development:
  host: localhost
  port: 5432
  adapter: postgresql
  encoding: unicode
  pool: 5
  database: recipe_app_dev
  username: postgres
  password: postgres

test:
  host: localhost
  port: 5432
  adapter: postgresql
  encoding: unicode
  pool: 5
  database: recipe_app_test
  username: postgres
  password: postgres

production:
  host: localhost
  port: 5432
  adapter: postgresql
  encoding: unicode
  pool: 5
  database: recipe_app_prod
  username: postgres
